// <auto-generated />
namespace AppData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _32 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_32));
        
        string IMigrationMetadata.Id
        {
            get { return "201610030219348_32"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
